
name: Snyk Scan

on:
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Create lockfile if it does NOT exist
      - name: Ensure lockfile exists
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Snyk
      - name: Install Snyk CLI
        run: npm install -g snyk@latest

      # Run Snyk Test
      - name: Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test
